[package]
name = "eksup"
version = "0.2.0-alpha4"
authors = ["Bryant Biggs <bryantbiggs@gmail.com>"]
description = "A CLI to aid in upgrading Amazon EKS clusters"
documentation = "https://github.com/clowdhaus/eksup"
homepage = "https://github.com/clowdhaus/eksup"
repository = "https://github.com/clowdhaus/eksup"
license = "Apache-2.0"
edition = "2021"
keywords = [
  "kubernetes",
  "eks",
]
categories = [
  "command-line-utilities",
  "text-processing",
]
exclude = ["/.github", ".gitignore", "docs", "examples", "tests"]

default-run = "eksup"

[[bin]]
name = "eksup"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
aws-config = "0.55"
aws-sdk-autoscaling = "0.25"
aws-sdk-ec2 = "0.25"
aws-sdk-eks = "0.25"
aws-types = "0.55"
indicatif = "0.16.2"
clap = { version = "4.0", features = ["derive", "string"] }
clap-verbosity-flag = "2.0"
handlebars = { version = "4.3", features = ["rust-embed"] }
itertools = "0.10"
# https://kube.rs/kubernetes-version/
k8s-openapi = { version = "0.18.0", default-features = false, features = ["v1_22"] }
kube = { version = "0.82.0", default-features = false, features = [ "client", "derive", "rustls-tls" ] }
rust-embed = { version = "6.4", features = ["compression"] }
schemars = "0.8"
seq-macro = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tabled = "0.10"
tokio = { version = "1.23", features = ["full"] }
tracing = {version = "0.1", features = ["log-always"] }
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
